<template>
  <div class="FeedScreen">
    <div class="Frame43266">
      <div class="Chatter">CHATTER</div>
      <div class="Frame43288">
        <div class="TrendingTags">Trending Tags</div>
        <div class="EvaTrendingUpOutline"> </div>
      </div>
      <div class="Frame43289">
        <div class="Programming">Programming</div>
        <div class="DataScience">Data science</div>
        <div class="Technology">Technology</div>
        <div class="MachineLearning">Machine learning</div>
        <div class="Politics">Politics</div>
      </div>
      <div class="SeeAll">See all</div>
      <div class="Personal">Personal</div>
      <div class="Overview">Overview</div>
      <div class="Frame43293">
        <div class="Frame43292">
          <div class="Frame43290">
            <div class="MdiAccountOutline"> </div>
            <div class="Account">Account</div>
          </div>
        </div>
        <div class="Frame43291">
          <div class="BasilNotificationOutline"> </div>
          <div class="Notifications">Notifications</div>
        </div>
      </div>
      <div class="Frame43335">
        <div class="Frame43287">
          <div class="Frame43270">
            <div class="IconsaxLinearFtxtoken"> </div>
            <div class="Feed">Feed</div>
          </div>
          <div class="Frame43271">
            <div class="MaterialSymbolsBookmarksOutline"> </div>
            <div class="Bookmarks">Bookmarks</div>
          </div>
          <div class="Frame43285">
            <div class="AntDesignTeamOutlined"> </div>
            <div class="TeamBlogs">Team blogs</div>
          </div>
          <div class="Frame43286">
            <div class="MaterialSymbolsDraftsOutline"> </div>
            <div class="Drafts">Drafts</div>
          </div>
        </div>
        <div class="Frame43334">
          <div class="IcOutlineAnalytics"> </div>
          <div class="Analytics">Analytics</div>
        </div>
      </div>
      <div class="LogOut">Log out</div>
    </div>
    <div class="Frame43267">
      <div class="Frame43268">
        <div class="RiSearchLine"> </div>
        <div class="SearchChatter">search chatter</div>
      </div>
      <div class="Frame43269">
        <div class="BasilNotificationOutline"> </div>
        <div class="MaskGroup">
          <div class="Ellipse5"> </div>
          <img
            class="UnsplashFhxpgmdXhe"
            src="https://via.placeholder.com/53x51"
            alt=""
          />
        </div>
      </div>
    </div>
    <div class="Frame43294">
      <div class="Frame43333">
        <div class="Frame43295">
          <div class="Feed">FEED</div>
          <div class="ExploreDifferentContentYouDLove">
            Explore different content you’d love
          </div>
        </div>
        <div class="Frame43296">
          <div class="IconParkOutlineWrite"> </div>
          <div class="PostAContent">Post a content</div>
        </div>
      </div>
      <div class="Frame43300">
        <div class="Line23"> </div>
        <div class="Line24"> </div>
        <div class="Frame43332">
          <div class="Frame43331">
            <div class="Frame43329">
              <div class="Frame43328">
                <div class="Frame43327">
                  <div class="Frame43326">
                    <div class="MaskGroup">
                      <div class="Ellipse5"> </div>
                      <img
                        class="UnsplashFhxpgmdXhe"
                        src="https://via.placeholder.com/105x103"
                        alt=""
                      />
                    </div>
                    <div class="Frame43325">
                      <div class="AdebobolaMuhydeen">Adebobola Muhydeen</div>
                      <div class="Frame43324">
                        <div class="PoliticalAnalyst">Political analyst</div>
                        <div class="May23rd2023">.May 23rd, 2023</div>
                      </div>
                    </div>
                  </div>
                  <div class="TheImpactOfSocialMediaOnPoliticalDiscourse">
                    The Impact of social media on Political discourse
                  </div>
                </div>
                <div class="Frame43304">
                  <div class="AntDesignReadOutlined"> </div>
                  <div class="MinsRead">10 mins read</div>
                </div>
              </div>
              <div
                class="InTheEraOfDigitalCommunicationSocialMediaPlatformsHaveBecomePervasiveInOurDailyLivesRevolutionizingTheWayWeConnectShareInformationAndEngageWithTheWorld"
              >
                In the era of digital communication, social media platforms have
                become pervasive in our daily lives, revolutionizing the way we
                connect, share information, and engage with the world
              </div>
            </div>
            <div class="Frame43330">
              <img
                class="UnsplashWqlglhjr6og"
                src="https://via.placeholder.com/612x242"
                alt=""
              />
            </div>
          </div>
          <div class="Frame43311">
            <div class="Frame43308">
              <div class="AntDesignCommentOutlined"> </div>
              <div>200</div>
            </div>
            <div class="Frame43309">
              <div class="MaterialSymbolsFavoriteOutline"> </div>
              <div>120</div>
            </div>
            <div class="Frame43310">
              <div class="IcOutlineAnalytics"> </div>
              <div class="Views">2980 views</div>
            </div>
          </div>
        </div>
        <div class="Frame43314">
          <div class="Frame43313">
            <div class="Frame43312">
              <div class="Frame43306">
                <div class="Frame43303">
                  <div class="MaskGroup">
                    <div class="Ellipse2"> </div>
                    <img
                      class="UnsplashJzz3jwmzha"
                      src="https://via.placeholder.com/105x103"
                      alt=""
                    />
                  </div>
                  <div class="Frame43302">
                    <div class="GraceIkpang">Grace Ikpang</div>
                    <div class="Frame43301">
                      <div class="ProductDesigner">Product designer</div>
                      <div class="May25th2023">.May 25th, 2023</div>
                    </div>
                  </div>
                </div>
                <div class="Frame43305">
                  <div class="StartingOutAsAProductDesigner">
                    Starting out as a Product designer
                  </div>
                  <div class="Frame43304">
                    <div class="AntDesignReadOutlined"> </div>
                    <div class="MinsRead">10 mins read</div>
                  </div>
                </div>
              </div>
              <div
                class="EmbarkingOnAJourneyAsAProductDesignerCanBeAnExhilaratingAndFulfillingExperienceAsAProfessionThatBridgesTheRealmsOfArtTechnologyAndProblemSolvingProductDesignOffersAnOpportunityToShapeTheWayPeopleInteractWithTheWorldAroundThem"
              >
                Embarking on a journey as a product designer can be an
                exhilarating and fulfilling experience. As a profession that
                bridges the realms of art, technology, and problem-solving,
                product design offers an opportunity to shape the way people
                interact with the world around them.
              </div>
            </div>
            <div class="Frame43307">
              <img
                class="UnsplashZvmziw3vdsq"
                src="https://via.placeholder.com/612x242"
                alt=""
              />
            </div>
          </div>
          <div class="Frame43311">
            <div class="Frame43308">
              <div class="AntDesignCommentOutlined"> </div>
              <div>200</div>
            </div>
            <div class="Frame43309">
              <div class="MaterialSymbolsFavoriteOutline"> </div>
              <div>120</div>
            </div>
            <div class="Frame43310">
              <div class="IcOutlineAnalytics"> </div>
              <div class="Views">2980 views</div>
            </div>
          </div>
        </div>
        <div class="Frame43323">
          <div class="Frame43322">
            <div class="Frame43321">
              <div class="Frame43320">
                <div class="Frame43319">
                  <div class="Frame43317">
                    <div class="MaskGroup">
                      <div class="Ellipse4"> </div>
                      <img
                        class="UnsplashIeebwgy6la"
                        src="https://via.placeholder.com/105x103"
                        alt=""
                      />
                    </div>
                    <div class="Frame43316">
                      <div class="OluwatobiOgunniyi">Oluwatobi Ogunniyi</div>
                      <div class="Frame43315">
                        <div class="SoftwareDeveloper">Software developer</div>
                        <div class="May22nd2023">.May 22nd, 2023</div>
                      </div>
                    </div>
                  </div>
                  <div class="UsingCssSelectors">Using CSS Selectors</div>
                </div>
                <div class="Frame43304">
                  <div class="AntDesignReadOutlined"> </div>
                  <div class="MinsRead">10 mins read</div>
                </div>
              </div>
              <div
                class="CascadingStyleSheetsCssIsAFundamentalTechnologyThatLiesAtTheHeartOfModernWebDesignItEmpowersDevelopersAndDesignersToTransformPlainHtmlIntoVisuallyCaptivatingAndInteractiveWebPages"
              >
                Cascading Style Sheets (CSS) is a fundamental technology that
                lies at the heart of modern web design. It empowers developers
                and designers to transform plain HTML into visually captivating
                and interactive web pages
              </div>
            </div>
            <div class="Frame43318">
              <img
                class="Unsplash6jvlsdgmace"
                src="https://via.placeholder.com/612x242"
                alt=""
              />
            </div>
          </div>
          <div class="Frame43311">
            <div class="Frame43308">
              <div class="AntDesignCommentOutlined"> </div>
              <div>200</div>
            </div>
            <div class="Frame43309">
              <div class="MaterialSymbolsFavoriteOutline"> </div>
              <div>120</div>
            </div>
            <div class="Frame43310">
              <div class="IcOutlineAnalytics"> </div>
              <div class="Views">2980 views</div>
            </div>
          </div>
        </div>
      </div>
      <div class="Frame43297">
        <div class="Frame43299">
          <div class="Frame43298">
            <div class="ForYou">For you</div>
            <div class="Rectangle35"> </div>
          </div>
          <div class="Featured">Featured</div>
          <div class="Recent">Recent</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style>
.Frame43308 > div {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43309 > div {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43308 > div {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43309 > div {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43308 > div {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43309 > div {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.FeedScreen {
  width: 100%;
  height: 100%;
  position: relative;
  background: white;
}

.Frame43266 {
  width: 268px;
  height: 2308px;
  left: 0px;
  top: 0px;
  position: absolute;
  border: 0.5px #d0d0d0 solid;
}

.Chatter {
  left: 72px;
  top: 10px;
  position: absolute;
  color: #543ee0;
  font-size: 32px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 48px;
  word-wrap: break-word;
}

.Frame43288 {
  width: 179px;
  height: 41px;
  left: 72px;
  top: 415px;
  position: absolute;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.TrendingTags {
  color: #111111;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.EvaTrendingUpOutline {
  width: 24px;
  height: 24px;
  position: relative;
}

.Evatrendingupoutline2 {
  width: 18.01px;
  height: 12px;
  left: 3px;
  top: 6px;
  position: absolute;
  background: #626262;
}

.Frame43289 {
  height: 183px;
  left: 90px;
  top: 468px;
  position: absolute;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.Programming {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.DataScience {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Technology {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.MachineLearning {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Politics {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.SeeAll {
  left: 89px;
  top: 664px;
  position: absolute;
  color: #543ee0;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Personal {
  left: 73px;
  top: 715px;
  position: absolute;
  color: #111111;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Overview {
  left: 73px;
  top: 82px;
  position: absolute;
  color: #111111;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43293 {
  left: 88px;
  top: 754px;
  position: absolute;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.Frame43292 {
  width: 136px;
  height: 42px;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43290 {
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.MdiAccountOutline {
  width: 24px;
  height: 24px;
  position: relative;
}

.Vector {
  width: 16px;
  height: 16px;
  left: 4px;
  top: 4px;
  position: absolute;
  background: #626262;
}

.Account {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43291 {
  height: 42px;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.BasilNotificationOutline {
  width: 24px;
  height: 24px;
  position: relative;
}

.Notifications {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43335 {
  left: 89px;
  top: 133px;
  position: absolute;
  flex-direction: column;
  justify-content: center;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.Frame43287 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-end;
  gap: 12px;
  display: flex;
}

.Frame43270 {
  width: 170px;
  height: 42px;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.IconsaxLinearFtxtoken {
  width: 24px;
  height: 24px;
  position: relative;
}

.Feed {
  color: #543ee0;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43271 {
  width: 174px;
  height: 42px;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.MaterialSymbolsBookmarksOutline {
  width: 24px;
  height: 24px;
  position: relative;
}

.Bookmarks {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43285 {
  width: 174px;
  height: 42px;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.AntDesignTeamOutlined {
  width: 24px;
  height: 24px;
  position: relative;
}

.TeamBlogs {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43286 {
  width: 174px;
  height: 42px;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.MaterialSymbolsDraftsOutline {
  width: 24px;
  height: 24px;
  position: relative;
}

.Drafts {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43334 {
  width: 167px;
  height: 42px;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.IcOutlineAnalytics {
  width: 24px;
  height: 24px;
  position: relative;
}

.Analytics {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.LogOut {
  left: 89px;
  top: 874px;
  position: absolute;
  color: #ff1400;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43267 {
  height: 66px;
  padding-top: 9px;
  padding-bottom: 9px;
  padding-left: 310px;
  padding-right: 129px;
  left: 268px;
  top: 0px;
  position: absolute;
  border: 0.5px #d0d0d0 solid;
  justify-content: flex-end;
  align-items: flex-start;
  gap: 189px;
  display: inline-flex;
}

.Frame43268 {
  width: 459px;
  align-self: stretch;
  border-radius: 8px;
  border: 0.5px #d0d0d0 solid;
  justify-content: flex-start;
  align-items: center;
  gap: 24px;
  display: inline-flex;
}

.RiSearchLine {
  padding-left: 12px;
  padding-right: 12px;
  padding-top: 8px;
  padding-bottom: 8px;
  justify-content: center;
  align-items: center;
  gap: 8px;
  display: flex;
}

.SearchChatter {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43269 {
  align-self: stretch;
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.MaskGroup {
  width: 48px;
  height: 48px;
  position: relative;
}

.Ellipse5 {
  width: 48px;
  height: 48px;
  left: 0px;
  top: 0px;
  position: absolute;
  background: #d9d9d9;
  border-radius: 9999px;
}

.UnsplashFhxpgmdXhe {
  width: 52.68px;
  height: 51.34px;
  left: -2.49px;
  top: -1.82px;
  position: absolute;
}

.Frame43294 {
  width: 1076px;
  height: 2212px;
  left: 292px;
  top: 96px;
  position: absolute;
  border: 0.5px #d0d0d0 solid;
}

.Frame43333 {
  left: 111px;
  top: 22px;
  position: absolute;
  justify-content: flex-start;
  align-items: center;
  gap: 380px;
  display: inline-flex;
}

.Frame43295 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.ExploreDifferentContentYouDLove {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43296 {
  width: 177px;
  padding-left: 16px;
  padding-right: 16px;
  padding-top: 8px;
  padding-bottom: 8px;
  background: #543ee0;
  border-radius: 8px;
  justify-content: center;
  align-items: center;
  gap: 8px;
  display: flex;
}

.IconParkOutlineWrite {
  width: 24px;
  height: 24px;
  position: relative;
}

.Group {
  width: 19.8px;
  height: 19.8px;
  left: 2.66px;
  top: 1.95px;
  position: absolute;
}

.PostAContent {
  color: white;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 700;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43300 {
  width: 854px;
  height: 1952px;
  left: 111px;
  top: 238px;
  position: absolute;
  border-radius: 8px;
  overflow: hidden;
  border: 0.5px #d0d0d0 solid;
}

.Line23 {
  width: 854px;
  height: 0px;
  left: 0px;
  top: 675px;
  position: absolute;
  border: 0.5px #d0d0d0 solid;
}

.Line24 {
  width: 854px;
  height: 0px;
  left: 0px;
  top: 1337px;
  position: absolute;
  border: 0.5px #d0d0d0 solid;
}

.Frame43332 {
  left: 40px;
  top: 1360px;
  position: absolute;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.Frame43331 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43329 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 24px;
  display: flex;
}

.Frame43328 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43327 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43326 {
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.Frame43325 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.AdebobolaMuhydeen {
  width: 249px;
  height: 36px;
  color: #111111;
  font-size: 24px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 36px;
  word-wrap: break-word;
}

.Frame43324 {
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
  display: inline-flex;
}

.PoliticalAnalyst {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.May23rd2023 {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.TheImpactOfSocialMediaOnPoliticalDiscourse {
  color: #111111;
  font-size: 32px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 48px;
  word-wrap: break-word;
}

.Frame43304 {
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
  display: inline-flex;
}

.AntDesignReadOutlined {
  width: 24px;
  height: 24px;
  position: relative;
}

.MinsRead {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.InTheEraOfDigitalCommunicationSocialMediaPlatformsHaveBecomePervasiveInOurDailyLivesRevolutionizingTheWayWeConnectShareInformationAndEngageWithTheWorld {
  width: 706px;
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43330 {
  width: 612px;
  height: 242px;
  background: #d0d0d0;
  border-radius: 8px;
  overflow: hidden;
  justify-content: center;
  align-items: center;
  display: inline-flex;
}

.UnsplashWqlglhjr6og {
  width: 612px;
  height: 242px;
  border-radius: 8px;
}

.Frame43311 {
  justify-content: flex-start;
  align-items: center;
  gap: 185px;
  display: inline-flex;
}

.Frame43308 {
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: flex;
}

.AntDesignCommentOutlined {
  width: 24px;
  height: 24px;
  position: relative;
}

.Frame43309 {
  justify-content: flex-start;
  align-items: center;
  gap: 8px;
  display: flex;
}

.MaterialSymbolsFavoriteOutline {
  width: 24px;
  height: 24px;
  position: relative;
}

.Frame43310 {
  justify-content: flex-start;
  align-items: center;
  gap: 8px;
  display: flex;
}

.Views {
  color: #626262;
  font-size: 16px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 24px;
  word-wrap: break-word;
}

.Frame43314 {
  left: 44px;
  top: 30px;
  position: absolute;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.Frame43313 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43312 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 24px;
  display: flex;
}

.Frame43306 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43303 {
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.Ellipse2 {
  width: 96px;
  height: 96px;
  left: 0px;
  top: 0px;
  position: absolute;
  background: #d9d9d9;
  border-radius: 9999px;
}

.UnsplashJzz3jwmzha {
  width: 105.35px;
  height: 102.68px;
  left: 0px;
  top: -3.65px;
  position: absolute;
}

.Frame43302 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
  display: inline-flex;
}

.GraceIkpang {
  color: #111111;
  font-size: 24px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 36px;
  word-wrap: break-word;
}

.Frame43301 {
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
  display: inline-flex;
}

.ProductDesigner {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.May25th2023 {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43305 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
  display: flex;
}

.StartingOutAsAProductDesigner {
  width: 526px;
  color: #111111;
  font-size: 32px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 48px;
  word-wrap: break-word;
}

.EmbarkingOnAJourneyAsAProductDesignerCanBeAnExhilaratingAndFulfillingExperienceAsAProfessionThatBridgesTheRealmsOfArtTechnologyAndProblemSolvingProductDesignOffersAnOpportunityToShapeTheWayPeopleInteractWithTheWorldAroundThem {
  width: 620px;
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43307 {
  width: 612px;
  height: 242px;
  background: #d0d0d0;
  justify-content: center;
  align-items: center;
  display: inline-flex;
}

.UnsplashZvmziw3vdsq {
  width: 612px;
  height: 242px;
  border-radius: 8px;
}

.Frame43323 {
  left: 44px;
  top: 695px;
  position: absolute;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.Frame43322 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43321 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 24px;
  display: flex;
}

.Frame43320 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 8px;
  display: flex;
}

.Frame43319 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: flex;
}

.Frame43317 {
  justify-content: flex-start;
  align-items: center;
  gap: 12px;
  display: inline-flex;
}

.Ellipse4 {
  width: 96px;
  height: 96px;
  left: 0px;
  top: 0px;
  position: absolute;
  background: #d9d9d9;
  border-radius: 9999px;
}

.UnsplashIeebwgy6la {
  width: 105.35px;
  height: 102.68px;
  left: -4.36px;
  top: 0px;
  position: absolute;
}

.Frame43316 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 12px;
  display: inline-flex;
}

.OluwatobiOgunniyi {
  color: #111111;
  font-size: 24px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 36px;
  word-wrap: break-word;
}

.Frame43315 {
  justify-content: flex-start;
  align-items: center;
  gap: 8px;
  display: inline-flex;
}

.SoftwareDeveloper {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.May22nd2023 {
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.UsingCssSelectors {
  color: #111111;
  font-size: 32px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 48px;
  word-wrap: break-word;
}

.CascadingStyleSheetsCssIsAFundamentalTechnologyThatLiesAtTheHeartOfModernWebDesignItEmpowersDevelopersAndDesignersToTransformPlainHtmlIntoVisuallyCaptivatingAndInteractiveWebPages {
  width: 592px;
  color: #626262;
  font-size: 18px;
  font-family: DM Sans;
  font-weight: 400;
  line-height: 27px;
  word-wrap: break-word;
}

.Frame43318 {
  width: 612px;
  height: 242px;
  border-radius: 8px;
  overflow: hidden;
  border: 0.5px #d0d0d0 solid;
  justify-content: center;
  align-items: center;
  display: inline-flex;
}

.Unsplash6jvlsdgmace {
  width: 612px;
  height: 242px;
  border-radius: 8px;
}

.Frame43297 {
  padding-top: 22px;
  padding-left: 51px;
  padding-right: 57px;
  left: 110px;
  top: 158px;
  position: absolute;
  border-radius: 8px;
  overflow: hidden;
  border: 0.5px #d0d0d0 solid;
  justify-content: flex-start;
  align-items: center;
  display: inline-flex;
}

.Frame43299 {
  align-self: stretch;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 240px;
  display: inline-flex;
}

.Frame43298 {
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  gap: 16px;
  display: inline-flex;
}

.ForYou {
  color: #111111;
  font-size: 24px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 36px;
  word-wrap: break-word;
}

.Rectangle35 {
  width: 84px;
  height: 6px;
  background: #543ee0;
}

.Featured {
  color: #111111;
  font-size: 24px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 36px;
  word-wrap: break-word;
}

.Recent {
  color: #111111;
  font-size: 24px;
  font-family: DM Sans;
  font-weight: 500;
  line-height: 36px;
  word-wrap: break-word;
}
</style>